//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class clienteMayorista
{
    public int idClienteMayorista { get; set; }
    public string nombre { get; set; }
    public string dpi { get; set; }
    public string direccion { get; set; }
    public string telefono { get; set; }
    public string Porcentaje_Pactado { get; set; }
}

public partial class clienteMinorista
{
    public int idClienteMinorista { get; set; }
    public string nombre { get; set; }
    public string dpi { get; set; }
    public string direccion { get; set; }
    public string telefono { get; set; }
    public string Pago_Alquiler { get; set; }
}
